name: Django CI/CD Deployment

on:
  push:
    branches: [ "main", "master" ]  # main 또는 master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. 프로젝트 폴더로 이동
            cd ~/Silk_Road
            
            # 2. 로컬 변경사항 임시 저장
            git stash
            
            # 3. 최신 코드 다운로드
            git pull origin main
            
            # (Optional) 2-1. 임시 저장한 변경사항 다시 적용 (충돌 발생 시 수동 해결 필요)
            # git stash pop
            
            # 4. 가상환경 켜기
            source venv/bin/activate
            
            # 5. 패키지 설치
            pip install -r requirements.txt
            
            # 6. 정적 파일 수집 및 DB 마이그레이션
            python manage.py collectstatic --noinput
            python manage.py migrate
            
            # 7. 서버 재시작
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx